# Ruff configuration with strictest settings
target-version = "py312"
line-length = 88

[lint]
select = ["ALL"]
ignore = [
    "D",      # pydocstyle - we'll handle docstrings separately
    "ANN101", # missing type annotation for self
    "ANN102", # missing type annotation for cls
    "COM812", # trailing comma - conflicts with formatter
    "ISC001", # implicit string concatenation - conflicts with formatter
    "TRY003", # Specific messages in exceptions
    "TRY300", # Consider else block - not always clearer
    "TRY400", # Use logging.exception - we handle it explicitly
    "EM101",  # Exception string literals
    "EM102",  # Exception f-strings
    "S608",   # SQL injection - we control inputs
    "PYI034", # __aenter__ return type
    "TCH003", # stdlib imports in type checking - not needed
]

[lint.per-file-ignores]
"tests/*" = [
    "S101",    # use of assert
    "PLR2004", # magic values in tests
    "PLR0913", # too many arguments
    "DTZ011",  # date.today() in tests is fine
]
"src/quickexpense/main.py" = [
    "INP001",  # implicit namespace package
]
"src/quickexpense/api/routes.py" = [
    "TCH001", # Type checking block - needed for circular import
]
# Legacy files - will be removed/refactored later
"main.py" = ["ALL"]
"config.py" = ["ALL"]
"models.py" = ["ALL"]
"oauth_setup.py" = ["ALL"]
"quickbooks_client.py" = ["ALL"]

[lint.isort]
known-first-party = ["quickexpense"]

[lint.mccabe]
max-complexity = 10

[lint.pep8-naming]
classmethod-decorators = [
    "classmethod",
    "pydantic.field_validator",
    "pydantic.model_validator",
]

[lint.pylint]
max-args = 5
max-branches = 12
max-returns = 6
max-statements = 50

[lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
